[project]
name = "astral_body"
version = "0.0.1"
dependencies = [
  "opencv-contrib-python==4.8.0.74",
  "mediapipe",
  "python-osc",
  "pandas",
  "requests"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
astral_body = "astral_body.cli:cli"
