// This is the identity dictionary that contains all things you might need to adjust for a performance.
// When playing "The Astral Body", modify this file and this file only.
// Before
~config = (
	player: 1, // The part you will be playing (1, 2, or 3)
	sensitivity: (
		wristOutward: 0.3, // How far out you have to place your hand to trigger certain sounds
		handsOverElbows: -0.3 // How far above your waist that certains sounds can be cued.
	)
)