// This is the identity dictionary that contains all things you might need to adjust for a performance.
// When playing "The Astral Body", modify this file and this file only.
// Before
~config = (
	player: 0, // The part you will be playing (0, 1, or 2)
	incrementScoreKeyCode: 65366, // PgDn key.
	sensitivity: (
		wristOutward: 0.3, // How far out you have to place your hand to trigger certain sounds
		wristUpward: 0.6, // How far up your wrist has to move to trigger certain sounds
		wristDownward: -0.2, // How far below your waist your wrist has to move to trigger certain sounds (negative is above the waist)
		handsOverElbows: -0.3, // How far above your waist that certains sounds can be cued.
		pan: 3 // Controls how much pan from left right position is multiplied by
	)
);
